// app/layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import ClientSessionProvider from "./ClientSessionProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import MobileFooter from "@/components/MobileFooter";
import { ProductProvider } from "@/context/ProductContext";  // Import ProductProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "New Fashion",
  description: "Generated by New Fashion",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientSessionProvider>
          <ProductProvider> {/* Wrap with ProductProvider */}
            <Navbar />
            {children}
            <MobileFooter />
            <Footer />
          </ProductProvider>
        </ClientSessionProvider>
      </body>
    </html>
  );
}

// app/layout.js
// import "./globals.css";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "New Fashion",
//   description: "Generated by New Fashion",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
